
// server和client的公共文件
#ifndef CHAT_PUBLIC_H_
#define CHAT_PUBLIC_H_

enum EnMsgType {
  LOGIN_MSG = 1,
  LOGIN_MSG_ACK,
  ONLINE_BROADCAST_MSG_ACK,
  REG_MSG,
  REG_MSG_ACK,
  TO_ONE_CHAT_MSG,
  ADD_FRIEND_MSG,
  ADD_FRIEND_MSG_ACK,
  ADD_FRIEND_REQ_MSG,
  ADD_FRIEND_REQ_LIST_MSG,
  ADD_FRIEND_REQ_LIST_MSG_ACK,
  ADD_FRIEND_RESP_MSG_ACK,
  DEL_FRIEND_MSG,
  DEL_FRIEND_MSG_ACK,
  CREATE_GROUP_MSG,
  CREATE_GROUP_MSG_ACK,
  JOIN_IN_GROUP_MSG,
  JOIN_IN_GROUP_MSG_ACK,
  GROUP_CHAT_MSG,
  LEAVE_GROUP_MSG,
  LEAVE_GROUP_MSG_ACK,
  LOGINOUT_MSG,
  REFRESHLISTS_MSG,
  REFRESHLISTS_MSG_ACK
};

#endif // CHAT_PUBLIC_H_